@port=http://localhost:3000
@accessToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcwMDczMzg3NywiZXhwIjoxNzAwNzM3NDc3fQ.YlRnf8dxPAa95tvL8wUPsWzyvKZrhroosF8I5mYaHjg
@refreshToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsImlhdCI6MTcwMDczMzg3NywiZXhwIjoxNzAwODIwMjc3fQ.iEn5_-_GroXEs54f1Bq5JjJVmpsk8A9SQPq3vBAD0lY
### 회원가입
POST {{port}}/api/auth/signup
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test123",
  "confirmPassword": "test123",
  "username": "관리자"
}

### 로그인
POST {{port}}/api/auth/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "test123"
}

### 로그아웃
GET {{port}}/api/auth/logout
Content-Type: application/json

### 사용자 상세정보 생성
POST {{port}}/api/user/me
Authorization: accesstoken:{{accessToken}}, refreshToken:{{refreshToken}}
Content-Type: application/json

{
  "profile": "프로필테스트",
  "region": "지역테스트",
  "nation": "국가테스트",
  "follow": "팔로우테스트"
}

### 내 정보 조회
GET {{port}}/api/user/me
Authorization: accesstoken:{{accessToken}}, refreshToken:{{refreshToken}}
Content-Type: application/json

### 내 정보 수정
PUT {{port}}/api/user/me
Authorization: accesstoken:{{accessToken}}, refreshToken:{{refreshToken}}
Content-Type: application/json

{
  "profile": "프로필변경테스트",
  "region": "지역변경테스트",
  "nation": "국가변경테스트",
  "follow": "팔로우변경테스트",
  "confirmPassword": "test123"
}

### 회원탈퇴
PUT {{port}}/api/user/me
Authorization: accesstoken:{{accessToken}}, refreshToken:{{refreshToken}}
Content-Type: application/json

{
  "confirmPassword": "test123"
}


// 게시글 기능
### 여행지등록
POST {{port}}/api/posts
Content-Type: application/json

{
  "title": "대방어철",
  "region": "겨울이되니깐",
  "contents": "배고픔"
}

### 광광지목록조회
GET {{port}}/posts
Content-Type: application/json

### 광광지개별조회
GET {{port}}/posts/8
Content-Type: application/json

### 광광지수정
PUT {{port}}/api/posts/24
Content-Type: application/json

{
  "title": "대방어철",
  "subtitle": "곧 없어질 녀석임",
  "region": "겨울이되니깐",
  "contents": "배고픔"
}

### 관광지삭제
DELETE {{port}}/api/posts/24
Content-Type: application/json

// 댓글 기능
### 댓글등록
POST {{port}}/api/posts/8/comments
Content-Type: application/json

{
  "text": "8번글에 댓글테스트입니다"
}

### 댓글조회
GET {{port}}/api/posts/8/comments
Content-Type: application/json

### 댓글수정
PUT {{port}}/api/posts/8/comments/2
Content-Type: application/json

{
  "text": "8번글에 댓글 수정 테스트입니다"
}

### 댓글삭제
DELETE {{port}}/api/posts/8/comments/2
Content-Type: application/json


// 팔로우기능
### 내가 팔로우하는 사람
GET {{port}}/api/user/my_follows
Content-Type: application/json

### 나를 팔로우하는 사람
GET {{port}}/api/user/my_followers
Content-Type: application/json

### 로그인2
POST {{port}}/api/auth/login
Content-Type: application/json

{
  "email": "visitor@example.com",
  "password": "102938"
}

### follow버튼 누르기
POST {{port}}/api/user/my_follows
Content-Type: application/json

{
  "targetId" : 39
}

### follow취소 누르기
DELETE {{port}}/api/user/my_follows
Content-Type: application/json

{
  "targetId" : 3
}

// 게시글 좋아요 기능

### 게시물 좋아요 버튼 누르기
POST {{port}}/api/posts/6/likes
Content-Type: application/json

### 게시물 좋아요 취소 누르기
DELETE {{port}}/api/posts/8/likes
Content-Type: application/json

### 내가 좋아하는 게시물 보기
GET {{port}}/api/user/my_liked_posts
Content-Type: application/json

### 특정글 좋아하는 사람 보기
GET {{port}}/api/posts/8/likes
Content-Type: application/json

// 댓글 좋아요 기능

### 댓글 좋아요 버튼 누르기
POST {{port}}/posts/:postId/comments/:commentId/likes
Content-Type: application/json

### 댓글 좋아요 취소 누르기
DELETE {{port}}/posts/:postId/comments/:commentId/likes
Content-Type: application/json

### 내가 좋아하는 댓글 보기
GET {{port}}/api/user/my_liked_comments
Content-Type: application/json

### 특정댓글 좋아하는 사람 보기
GET {{port}}/posts/:postId/comments/:commentId/likes
Content-Type: application/json